/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAluno;
import fatec.poo.control.DaoCurso;
import fatec.poo.control.DaoTurma;
import fatec.poo.control.Helper;
import fatec.poo.model.APrazo;
import fatec.poo.model.AVista;
import fatec.poo.model.Aluno;
import fatec.poo.model.Curso;
import fatec.poo.model.Matricula;
import fatec.poo.model.Turma;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class GuiAlocarEfetuarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form GuiAlocarEfetuarMatricula
     */
    public GuiAlocarEfetuarMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grbtPagamento = new javax.swing.ButtonGroup();
        lblDataMatricula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ftxtDataMatricula = new javax.swing.JFormattedTextField();
        cbxCurso = new javax.swing.JComboBox<>();
        cbxTurma = new javax.swing.JComboBox<>();
        ftxtCPFAluno = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAgencia = new javax.swing.JLabel();
        lblQtdeMensalidade = new javax.swing.JLabel();
        lblnoCheque = new javax.swing.JLabel();
        lblDataPagto = new javax.swing.JLabel();
        lblTxJuros = new javax.swing.JLabel();
        lblDataVencto = new javax.swing.JLabel();
        ftxtDataPagto = new javax.swing.JFormattedTextField();
        txtAgencia = new javax.swing.JTextField();
        txtNoCheque = new javax.swing.JTextField();
        txtQtdeMensalidade = new javax.swing.JTextField();
        txtTxJuros = new javax.swing.JTextField();
        ftxtDataVencto = new javax.swing.JFormattedTextField();
        rbtParcelado = new javax.swing.JRadioButton();
        rbtAVista = new javax.swing.JRadioButton();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Efetuar Matricula");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblDataMatricula.setText("Data da Matrícula ");

        jLabel2.setText("Curso");

        jLabel3.setText("Turma");

        jLabel4.setText("CPF Aluno");

        try {
            ftxtDataMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCursoActionPerformed(evt);
            }
        });

        cbxTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTurmaActionPerformed(evt);
            }
        });

        try {
            ftxtCPFAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Valor");

        jLabel6.setText("Nome");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));

        lblAgencia.setText("Agência");

        lblQtdeMensalidade.setText("Qtde. Mensalidades");

        lblnoCheque.setText("No. Cheque");

        lblDataPagto.setText("Data Pagto.");

        lblTxJuros.setText("Tx. Juros(%)");

        lblDataVencto.setText("Data 1o. Vencto.");

        try {
            ftxtDataPagto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtDataVencto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        grbtPagamento.add(rbtParcelado);
        rbtParcelado.setText("Parcelado");

        grbtPagamento.add(rbtAVista);
        rbtAVista.setText("À Vista");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtParcelado)
                        .addGap(18, 18, 18)
                        .addComponent(lblQtdeMensalidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdeMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(lblTxJuros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTxJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblDataVencto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtDataVencto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtAVista)
                        .addGap(18, 18, 18)
                        .addComponent(lblAgencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblnoCheque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblDataPagto)
                        .addGap(18, 18, 18)
                        .addComponent(ftxtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgencia)
                    .addComponent(lblnoCheque)
                    .addComponent(lblDataPagto)
                    .addComponent(ftxtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtAVista))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdeMensalidade)
                    .addComponent(lblTxJuros)
                    .addComponent(txtQtdeMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataVencto)
                    .addComponent(ftxtDataVencto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTxJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtParcelado))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        lblValor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblNome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataMatricula)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftxtDataMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(cbxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxTurma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(125, 125, 125)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ftxtCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnConsultar, btnExcluir, btnInserir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataMatricula)
                    .addComponent(ftxtDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftxtCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(Sair))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("poo", "trabalhopoo");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoCurso = new DaoCurso(conexao.conectar());
        daoTurma = new DaoTurma(conexao.conectar());
        daoAVista = new DaoAVista(conexao.conectar());
        daoAPrazo = new DaoAPrazo(conexao.conectar());

        cursos = new ArrayList<>();
        cursos = daoCurso.listarSiglas(cursos);
        for (int i = 0; i < cursos.size(); i++) {
            cbxCurso.addItem(cursos.get(i));
        }

        cbxCurso.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                curso = daoCurso.consultar(cbxCurso.getSelectedItem().toString());
                lblValor.setText(Double.toString(curso.getValor()));
            }
        });

        ftxtCPFAluno.setEnabled(false);
        rbtAVista.setEnabled(false);
        rbtParcelado.setEnabled(false);
        txtAgencia.setEnabled(false);
        txtNoCheque.setEnabled(false);
        ftxtDataPagto.setEnabled(false);
        txtTxJuros.setEnabled(false);
        txtQtdeMensalidade.setEnabled(false);
        ftxtDataVencto.setEnabled(false);

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        conexao.fecharConexao();
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void cbxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCursoActionPerformed
        cbxTurma.removeAllItems();
        String sc = String.valueOf(cbxCurso.getSelectedItem());
        turmas = new ArrayList<>();
        turmas = daoTurma.listarTurmasCurso(turmas, sc);
        for (int i = 0; i < turmas.size(); i++) {
            cbxTurma.addItem(turmas.get(i));
        }
    }//GEN-LAST:event_cbxCursoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String cpf = ftxtCPFAluno.getText().replaceAll("[.-]", "");
        System.out.println(helper.isCpfValid(cpf));
        if (helper.isCpfValid(cpf)) {
            lblNome.setEnabled(true);
            Aluno aluno = daoAluno.consultar(cpf);
            if (aluno != null) {
                lblNome.setText(aluno.getNome());
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF Invalido");
            ftxtCPFAluno.setEnabled(true);
            ftxtCPFAluno.requestFocus();
            ftxtCPFAluno.setText("");

        }

        btnConsultar.setEnabled(false);
        btnInserir.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);


    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        matricula = new Matricula(ftxtDataMatricula.getText());
        aVista = new AVista();
        aPrazo = new APrazo();

        boolean teste = rbtAVista.isSelected();
        if (teste == true) {
            aVista.setAgencia(Integer.valueOf(txtAgencia.getText()));
            aVista.setnCheque(Integer.valueOf(txtNoCheque.getText()));
            aVista.setPreData(ftxtDataPagto.getText());

            daoAVista.inserir(aVista);

            txtAgencia.setText("");
            txtNoCheque.setText("");
            ftxtDataPagto.setText("");

            btnInserir.setEnabled(false);
            txtAgencia.setEnabled(true);
            txtNoCheque.setEnabled(true);
            ftxtDataPagto.setEnabled(true);

            txtQtdeMensalidade.setEnabled(false);
            txtTxJuros.setEnabled(false);
            ftxtDataVencto.setEnabled(false);
            ftxtDataMatricula.requestFocus();

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);

        } else {

            aPrazo.setQtdeMensalidade(Integer.valueOf(txtQtdeMensalidade.getText()));
            aPrazo.setTaxaJuros(Integer.valueOf(txtTxJuros.getText()));
            aPrazo.setDataVencimento(ftxtDataVencto.getText());

            daoAPrazo.inserir(aPrazo);

            txtQtdeMensalidade.setText("");
            txtTxJuros.setText("");
            ftxtDataVencto.setText("");

            btnInserir.setEnabled(false);
            txtQtdeMensalidade.setEnabled(true);
            txtTxJuros.setEnabled(true);
            ftxtDataVencto.setEnabled(true);

            txtAgencia.setEnabled(false);
            txtNoCheque.setEnabled(false);
            ftxtDataPagto.setEnabled(false);
            ftxtDataMatricula.requestFocus();

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração") == 0) {
            matricula = new Matricula(ftxtDataMatricula.getText());

            if (rbtAVista.isSelected()) {
                aVista.setAgencia(Integer.parseInt(txtAgencia.getText()));
                aVista.setnCheque(Integer.parseInt(txtNoCheque.getText()));
                aVista.setPreData(ftxtDataPagto.getText());

                daoAVista.alterar(aVista);

                txtAgencia.setText("");
                txtNoCheque.setText("");
                ftxtDataPagto.setText("");
                rbtAVista.requestFocus();

                rbtAVista.setEnabled(true);
                txtAgencia.setEnabled(false);
                txtNoCheque.setEnabled(false);
                ftxtDataPagto.setEnabled(false);

            } else {
                aPrazo.setQtdeMensalidade(Integer.parseInt(txtQtdeMensalidade.getText()));
                aPrazo.setTaxaJuros(Double.parseDouble(txtTxJuros.getText()));
                aPrazo.setDataVencimento(ftxtDataVencto.getText());

                daoAPrazo.alterar(aPrazo);

                txtQtdeMensalidade.setText("");
                txtTxJuros.setText("");
                ftxtDataVencto.setText("");
                rbtParcelado.requestFocus();

                rbtParcelado.setEnabled(true);
                txtQtdeMensalidade.setEnabled(false);
                txtTxJuros.setEnabled(false);
                ftxtDataVencto.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclusão?") == 0) {
            daoAVista.excluir(matricula);
            daoAPrazo.excluir(matricula);

            cbxCurso.setSelectedIndex(0);
            cbxTurma.setSelectedIndex(0);
            txtAgencia.setText("");
            txtNoCheque.setText("");
            txtQtdeMensalidade.setText("");
            txtTxJuros.setText("");
            ftxtCPFAluno.setText("");
            ftxtDataMatricula.setText("");
            ftxtDataPagto.setText("");
            ftxtDataVencto.setText("");

            cbxCurso.setEnabled(true);
            cbxTurma.setEnabled(true);
            ftxtDataMatricula.setEnabled(true);
            ftxtCPFAluno.setEnabled(false);
            ftxtDataPagto.setEnabled(false);
            ftxtDataVencto.setEnabled(false);
            rbtnAVista.setEnabled(false);
            rbtnAPrazo.setEnabled(false);
            txtAgencia.setEnabled(false);
            txtNoCheque.setEnabled(false);
            txtQtdeMensalidade.setEnabled(false);
            txtTxJuros.setEnabled(false);
            ftxtDataMatricula.requestFocus();

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbxTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTurmaActionPerformed
        ftxtCPFAluno.setEnabled(true);
        rbtAVista.setEnabled(true);
        rbtParcelado.setEnabled(true);
    }//GEN-LAST:event_cbxTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAlocarEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAlocarEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAlocarEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAlocarEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAlocarEfetuarMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox<String> cbxCurso;
    private javax.swing.JComboBox<String> cbxTurma;
    private javax.swing.JFormattedTextField ftxtCPFAluno;
    private javax.swing.JFormattedTextField ftxtDataMatricula;
    private javax.swing.JFormattedTextField ftxtDataPagto;
    private javax.swing.JFormattedTextField ftxtDataVencto;
    private javax.swing.ButtonGroup grbtPagamento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblDataMatricula;
    private javax.swing.JLabel lblDataPagto;
    private javax.swing.JLabel lblDataVencto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQtdeMensalidade;
    private javax.swing.JLabel lblTxJuros;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblnoCheque;
    private javax.swing.JRadioButton rbtAVista;
    private javax.swing.JRadioButton rbtParcelado;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtNoCheque;
    private javax.swing.JTextField txtQtdeMensalidade;
    private javax.swing.JTextField txtTxJuros;
    // End of variables declaration//GEN-END:variables
    private DaoCurso daoCurso = null;
    private DaoTurma daoTurma = null;
    private DaoAluno daoAluno = null;
    private DaoAVista daoAVista = null;
    private DaoAPrazo daoAPrazo = null;
    private Helper helper = new Helper();
    private Curso curso = null;
    private Turma turma = null;
    private Matricula matricula = null;
    private APrazo aPrazo = null;
    private AVista aVista = null;
    private Conexao conexao = null;
    ArrayList<String> cursos = null;
    ArrayList<String> turmas = null;
    ArrayList<String> alunos = null;
}
